BLACKLISTED_NICKNAMES = {
    "ana",
    "ana maria",
    "ana carolina",
    "ana paula",
    "ana claudia",
    "ana julia",
    "ana laura",
    "ana lucia",
    "ana luiza",
    "ana beatriz",
    "ana sofia",
    "ana clara",
    "anderson",
    "andre",
    "andrea",
    "andreia",
    "arthur",
    "augusto",
    "barbara",
    "beatriz",
    "brenda",
    "bruno",
    "camila",
    "carla",
    "carlos",
    "carolina",
    "carol",
    "catarina",
    "cecilia",
    "claudia",
    "cristian",
    "cristiane",
    "cristina",
    "daniel",
    "daniela",
    "danilo",
    "diego",
    "davi",
    "eduarda",
    "eduardo",
    "eliana",
    "elizabeth",
    "elisa",
    "elisangela",
    "emanuel",
    "emanuele",
    "emily",
    "enrico",
    "enzo",
    "erica",
    "erika",
    "estevao",
    "fabiana",
    "fabiano",
    "fabio",
    "felipe",
    "fernanda",
    "fernando",
    "flavia",
    "gabriel",
    "gabriela",
    "giovana",
    "giovanna",
    "giovanni",
    "gustavo",
    "helena",
    "helen",
    "henrique",
    "heloisa",
    "igor",
    "ingrid",
    "isabel",
    "isabela",
    "isabelly",
    "isadora",
    "israel",
    "ivan",
    "jaqueline",
    "joana",
    "joao",
    "joao pedro",
    "joao vitor",
    "joao paulo",
    "joao lucas",
    "joao gabriel",
    "jorge",
    "jose",
    "josefa",
    "julia",
    "juliana",
    "juliano",
    "julio",
    "karina",
    "karen",
    "karlos",
    "keila",
    "lara",
    "larissa",
    "laura",
    "leandro",
    "leticia",
    "lia",
    "lorena",
    "lorenzo",
    "lucas",
    "luciana",
    "luciano",
    "luigi",
    "luisa",
    "luiz",
    "luis",
    "luna",
    "luzia",
    "manoel",
    "marcela",
    "marcelo",
    "marcia",
    "marco",
    "marcos",
    "maria",
    "maria alice",
    "maria clara",
    "maria eduarda",
    "maria fernanda",
    "maria flor",
    "maria helena",
    "maria julia",
    "maria laura",
    "maria luiza",
    "maria sophia",
    "mariana",
    "mariane",
    "marina",
    "marta",
    "mateus",
    "matheus",
    "miguel",
    "mirella",
    "monica",
    "natalia",
    "nathalia",
    "nicole",
    "nicolas",
    "noemi",
    "patricia",
    "paula",
    "paulo",
    "pedro",
    "rafael",
    "rafaela",
    "raissa",
    "rebeca",
    "renan",
    "renata",
    "roberta",
    "roberto",
    "rodrigo",
    "rosa",
    "sabrina",
    "samuel",
    "sandra",
    "sara",
    "silvia",
    "simone",
    "sofia",
    "sofia maria",
    "sophia",
    "stefany",
    "stephanie",
    "suellen",
    "suelen",
    "tales",
    "talita",
    "tamires",
    "tatiana",
    "thais",
    "thales",
    "thiago",
    "valentina",
    "valeria",
    "vanessa",
    "vera",
    "victor",
    "victoria",
    "vinicius",
    "vitoria",
    "wagner",
    "wellington",
    "wesley",
    "william",
    "yasmin",
    "yasmim",
    "yuri",
    "aline",
    "amanda",
    "adriana",
    "alessandra",
    "alessandro",
    "alisson",
    "altair",
    "amelia",
    "ariadne",
    "ariel",
    "arlete",
    "armando",
    "aurora",
    "bianca",
    "bernardo",
    "caio",
    "calebe",
    "carine",
    "cinthia",
    "damiana",
    "domingos",
    "edgar",
    "edna",
    "erivana",
    "ester",
    "evelyn",
    "everton",
    "fatima",
    "filipe",
    "flor",
    "francisco",
    "geovana",
    "geovanna",
    "gilberto",
    "gilmar",
    "grazi",
    "graziela",
    "herika",
    "humberto",
    "ines",
    "janaina",
    "jeremias",
    "joel",
    "joice",
    "jonas",
    "judite",
    "lais",
    "laisla",
    "laiany",
    "leila",
    "lidia",
    "lorraine",
    "luciene",
    "ludmila",
    "luiz felipe",
    "luiz gustavo",
    "maicon",
    "malu",
    "marcio",
    "maristela",
    "marisa",
    "milena",
    "murilo",
    "nadia",
    "odair",
    "pamela",
    "priscila",
    "rafaella",
    "raquel",
    "ricardo",
    "rosana",
    "rosangela",
    "suelen",
    "telma",
    "vera lucia",
    "vilma",
    "violeta",
    "yasmin oliveira",
    "zilda",
}
